### ISSUE TITLE
How to Style?

### ISSUE THREAD

**Issue by swordsreversed** [draperd/react-forms-processor#58] opened 2019-03-18 10:31 UTC
I tried adding this to a custom renderer: 

```
case 'text': {
      return (
        <FieldText
          {...field}
          className='mainForm'
          shouldFitContainer='true'
          autoComplete='off'
          onChange={(event) => onChange(id, event.target.value)}
          onFocus={(event) => onFieldFocus(event)}
        />
      );
    }
```

But it doesnt seem to add the form and the elements i want to change are on the div above the input anyway.
```
.mainForm {
  width: 100%;
  border: 1px solid #999999 !important;
  border-radius: 5px;
  background: #f3f8f2 !important;
}
```

**Comment by draperd** [comment] 2019-03-19 08:59
Is the `FieldText` component you've used in the example you've provided one of your own or is it the Atlaskit component? If it's the latter then the issue is likely to be that the `className` attribute it not a valid property for that component or is being obfuscated due to implementation via the Styled Components CSS-in-JS implementation. 

If you want to style an element then you'd be better off wrapping the component in your own `div` element such that the CSS class is not obfuscated and then your selector will match. You might need to adjust your selector to target elements nested within the element containing your CSS class.

This isn't really anything that the React Forms Processor project can do anything about as it doesn't control the implementation of the fields that it ultimately renders - by design.

**Comment by draperd** [comment] 2019-03-30 10:17
I'm going to close this issue as there's been no follow up on it.

**Closed by draperd** 2019-03-30 10:17 UTC
