### ISSUE TITLE
multiselect loose defaultValue when create FormFragment 

### ISSUE THREAD

**Issue by glamer** [draperd/react-forms-processor#35] opened 2018-12-11 14:40 UTC

**Comment by draperd** [comment] 2018-12-11 23:50
Whilst I appreciate you taking the time to raise an issue and for trying out this library at all, it is somewhat essential that you provide more information to help investigate and resolve this problem. 

There are multiple instances of the multi-select components for each renderer so it's not clear if this refers to one or all instances. Also, you've not provided any steps for recreating the problem that you've encountered.

Providing a reproducible test case is essential for any bug report to be able to verify that the issue has been satisfactorily resolved. If you could provide some additional information I would be very grateful.

**Comment by glamer** [comment] 2018-12-12 15:13
Thanks for response. I created a test case in sandbox. [https://codesandbox.io/s/88n1n7plwj](url)
I run into this problem in all renderers.
When i 'm trying to provide defaultFields in FormFragment component , it loses default values.

**Comment by draperd** [comment] 2018-12-13 09:14
Thanks for the extra issue and for providing the sandbox example - it's much appreciated. I'm taking a look now.

**Comment by draperd** [comment] 2018-12-13 09:49
It looks like the issue is the result of the initial value being processed differently depending upon where the defaultFields are passed. It looks like defaultFields passed to the Form correctly derives the initial value, but passing a value does not.... whereas it looks like passing defaultFields to the FormFragment does not derive the correct initial value, but it will take the correct value if set on the Form.

I think I'll need to carefully review the functions, add some tests and get to the bottom of the problem

**Comment by draperd** [comment] 2018-12-13 11:03
I've created the linked PR, waiting for a review and will the publish a new version of the lib when merged.

**Closed** 2018-12-14 20:33 UTC

**Comment by glamer** [comment] 2018-12-17 11:21
Hi, Dave. I just tested 0.0.30 it looks like all works great , but i want to clear some thing. 
When i try to handle values from that multiselect , it works only once  after loading page and clicking save button. After changing some values and click the button again  i see empty values in console. Is this expected behaviour?   https://codesandbox.io/s/x3rqrpk09w

**Comment by draperd** [comment] 2019-01-09 15:13
I just want to check that the problem you describe in your last comment was raised as #37
