### ISSUE TITLE
The values in multiselect field are not saving

### ISSUE THREAD

**Issue by glamer** [draperd/react-forms-processor#37] opened 2018-12-19 09:39 UTC
this behaviour occurs after changing some values https://codesandbox.io/s/x3rqrpk09w

**Comment by draperd** [comment] 2019-01-08 21:33
Thanks for raising this issue, apologies for not getting to it sooner. I really appreciate you also taking the time to raise a PR identifying the cause of the problem.

I've created a slightly different fix with a test and merged that instead - but having your PR to base it on was incredibly helpful.

For my own future reference the cause of the problem was that the `splitDelimitedValue` function was returning an empty array for any non-string value. I would assume that my initial reasoning for this was that this would only be called with string values - however, I hadn't taken into consideration the fact that it would be called after the initial value was converted from a string to an array. Once converted the values should no longer be processed.

I think a better fix would be to ensure that the `splitDelimitedValue` function is only called when appropriate (e.g. only when setting the initial value), but the original proposed change is definitely a quick way of resolving the problem so I've gone for that initially so that I can publish a new version with the fix as quickly as possible.

**Comment by draperd** [comment] 2019-01-08 21:47
The fix for this issue is now available in version 0.0.32

**Closed by draperd** 2019-01-08 21:47 UTC
