### ISSUE TITLE
Checkbox not rendering value

### ISSUE THREAD

**Issue by rhugie** [draperd/react-forms-processor#54] opened 2019-03-07 03:55 UTC
When I pass in a checkbox value of true, it does not render the checkbox as being checked. Using the following JSON definition, the field1 and field2 values are shown but the checkbox shows as unchecked when it should be checked.

[{"id":"field1","name":"field1","type":"text","label":"Field 1","description":"","placeholder":"","defaultValue":"","value":"test"},{"id":"field2","name":"field2","type":"text","label":"Field 2","description":"","placeholder":"","defaultValue":"","value":"test2"},{"id":"check1","name":"check1","type":"checkbox","label":"Check 1","description":"","placeholder":"","defaultValue":"","value":true}]

**Comment by draperd** [comment] 2019-03-08 21:19
Thanks for point this out - you're quite right. I'll look into this asap and resolve the problem.

**Comment by draperd** [comment] 2019-03-09 02:25
It looks like this issue is specifically to do with the Atlaskit renderer - the native HTML and Material UI renderers seem to be initialising the checkbox just fine.

**Comment by draperd** [comment] 2019-03-09 02:33
Also... it looks like it's not just the Checkbox component but some of the others as well. I suspect that some recent refactoring may have introduced these problems. The Atlaskit package doesn't currently have any units tests - I'll add some during the fix to ensure that future regressions don't occur

**Comment by draperd** [comment] 2019-03-09 09:52
The fix for this is now available in 0.0.37

**Closed** 2019-03-09 09:52 UTC

**Comment by rhugie** [comment] 2019-03-15 04:11
Thanks for the quick turn around
